name: Deploy SvelteKit to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # non-sensitive config
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Export SvelteKit public envs
        run: |
          echo "PUBLIC_API_BASE_URL=${{ secrets.PUBLIC_API_BASE_URL }}" >> $GITHUB_ENV

      - name: Build SvelteKit app
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel --prod \
            --token $VERCEL_TOKEN \
            --org $VERCEL_ORG_ID \
            --project $VERCEL_PROJECT_ID \
            --yes
