name: Deploy to Vercel

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build

      # Optionally run tests/lint here

      - name: Deploy to Vercel
        run: npx vercel --prod --token=$VERCEL_TOKEN
